//! The full-corpus proof for Global Constraint 14 (ROADMAP Task 9.3):
//! **no secret this project knows how to recognize reaches any renderer's
//! output.**
//!
//! `tests/redact.rs` proves each redaction rule fires, one sentinel per
//! rule, on the serialized model. This file is the other half of the
//! claim and the one an operator actually depends on: the model is not
//! what gets pasted into a pull request — a terminal summary, a
//! `result.json`, a `report.html`, and a GitHub step summary are. Every
//! one of them is rendered here from a `LabResult` salted with
//! [`SENTINELS`], and every one of them is searched for every sentinel.
//!
//! # Why "reach" rather than a flat absence assertion
//!
//! Asserting only that a renderer's output lacks the sentinels is
//! satisfiable by a renderer that prints nothing, and two of these four
//! genuinely do print less than the whole document: the terminal summary
//! shows findings rather than every payload, and the GitHub summary
//! truncates each cell at `MAX_CELL_CHARS`. So each renderer is run
//! **twice** — once on the unredacted result to learn which sentinels it
//! can show at all (its *reach*), once on the redacted one to prove every
//! sentinel in that reach is gone. A renderer that stopped rendering
//! payloads would lose its reach and fail
//! [`every_renderer_reaches_some_sentinel_before_redaction`] rather than
//! passing this file vacuously.
//!
//! [`the_json_renderer_reaches_every_sentinel`] pins the strongest case:
//! `result.json` carries the whole document, so its reach must be the
//! complete corpus. That is what makes the corpus itself non-vacuous —
//! every sentinel really is somewhere in the input.
//!
//! # What the corpus covers
//!
//! One unique, greppable string per credential *shape*, not per rule, so
//! a rule that fires on the shape its author had in mind and misses a
//! sibling shape fails here:
//!
//! - bearer tokens, in an `Authorization:` line and in a captured header
//!   map;
//! - `Cookie`, `Set-Cookie`, `Proxy-Authorization`, `X-Api-Key` and
//!   `X-Auth-Token`, in free text and as object keys;
//! - credential-named environment literals in eight naming shapes
//!   (`DB_PASSWORD`, `MYSQL_PASSWD`, `SERVICE_PWD`, `SMTP_PASS`,
//!   `TLS_PASSPHRASE`, `API_TOKEN`, `AWS_SECRET_ACCESS_KEY`,
//!   `REGISTRY_CREDENTIAL`), reached through a final object, a semantic
//!   change payload, and a mutating webhook's JSON Patch;
//! - PEM private keys in four encodings (RSA, EC, PKCS#8, and a block
//!   truncated mid-body), plus **a real private key** generated by
//!   `admissionlab_gateway::generate_test_certificate` — the same call the
//!   Gateway suite makes, so this corpus contains the actual test-CA key
//!   material a run produces rather than a lookalike;
//! - a Secret's `data` and `stringData`, at the top level of a payload
//!   and inside a webhook patch that creates one;
//! - kubeconfig credential material: a `client-key-data:` line, a
//!   `token:` line, and the parsed-object forms of both.
//!
//! Every sentinel is `[a-z0-9-]` only, so no renderer's escaping (HTML
//! entities, Markdown backslashes) can hide one from a substring search
//! by rewriting its characters.
//!
//! # Global Constraint 15
//!
//! [`redaction_preserves_every_finding_and_its_shape`] and
//! [`every_redacted_location_still_shows_that_something_was_there`] are
//! the counterweight: a redaction pass that satisfied this file by
//! deleting the findings would be reporting that two stacks agreed when
//! they did not. Structure, grades, counts, and the *names* of every
//! redacted field survive; only the literals go.

mod support;

use std::path::{Path, PathBuf};
use std::sync::OnceLock;
use std::sync::atomic::{AtomicU64, Ordering};

use admissionlab_core::RedactedValue;
use admissionlab_report::{
    LabResult, REDACTED, REDACTED_PRIVATE_KEY, RedactionRules, RunSummary, TerminalOptions,
    redact_result, render_github_summary, render_terminal, write_html_report, write_json_report,
};
use serde_json::{Value, json};
use support::canonical_result;

// ---------------------------------------------------------------------
// The corpus
// ---------------------------------------------------------------------

/// Every planted secret, in the order the corpus is described in this
/// file's documentation.
const SENTINELS: &[&str] = &[
    AUTHORIZATION_TEXT,
    AUTHORIZATION_KEY,
    COOKIE_TEXT,
    SET_COOKIE_KEY,
    PROXY_AUTHORIZATION_TEXT,
    API_KEY_TEXT,
    API_KEY_MAP,
    AUTH_TOKEN_KEY,
    ENV_PASSWORD,
    ENV_PASSWD,
    ENV_PWD,
    ENV_PASS,
    ENV_PASSPHRASE,
    ENV_TOKEN,
    ENV_SECRET_ACCESS_KEY,
    ENV_CREDENTIAL,
    PEM_RSA,
    PEM_EC,
    PEM_PKCS8,
    PEM_TRUNCATED,
    SECRET_DATA,
    SECRET_STRING_DATA,
    SECRET_IN_PATCH,
    KUBECONFIG_CLIENT_KEY_TEXT,
    KUBECONFIG_CLIENT_KEY_FIELD,
    KUBECONFIG_TOKEN_TEXT,
    KUBECONFIG_TOKEN_FIELD,
    KUBECONFIG_PASSWORD_FIELD,
];

/// A bearer token on an `Authorization:` line inside an API-server
/// warning.
const AUTHORIZATION_TEXT: &str = "sentinel-authorization-line-a1";
/// The same token under an `authorization` object key in a captured
/// header map.
const AUTHORIZATION_KEY: &str = "sentinel-authorization-key-a2";
/// A session cookie on a `Cookie:` line inside a stale-expectation
/// reason.
const COOKIE_TEXT: &str = "sentinel-cookie-line-a3";
/// A `Set-Cookie` value in a live Gateway probe's response headers.
const SET_COOKIE_KEY: &str = "sentinel-set-cookie-key-a4";
/// A `Proxy-Authorization:` line inside a divergence explanation.
const PROXY_AUTHORIZATION_TEXT: &str = "sentinel-proxy-authorization-a5";
/// An `X-Api-Key:` line inside a first-divergence explanation.
const API_KEY_TEXT: &str = "sentinel-x-api-key-line-a6";
/// The same key under an `X-Api-Key` object key in a payload map.
const API_KEY_MAP: &str = "sentinel-x-api-key-map-a7";
/// An `x-auth-token` value in a Gateway probe's response headers.
const AUTH_TOKEN_KEY: &str = "sentinel-x-auth-token-key-a8";

/// `DB_PASSWORD`'s literal, in a final object's container env.
const ENV_PASSWORD: &str = "sentinel-env-password-b1";
/// `MYSQL_PASSWD`'s literal — the abbreviated spelling.
const ENV_PASSWD: &str = "sentinel-env-passwd-b2";
/// `SERVICE_PWD`'s literal — the doubly-abbreviated spelling.
const ENV_PWD: &str = "sentinel-env-pwd-b3";
/// `SMTP_PASS`'s literal — the shape the longer spellings miss.
const ENV_PASS: &str = "sentinel-env-pass-b4";
/// `TLS_PASSPHRASE`'s literal.
const ENV_PASSPHRASE: &str = "sentinel-env-passphrase-b5";
/// `API_TOKEN`'s literal, injected by a mutating webhook's JSON Patch
/// rather than present in the submitted object.
const ENV_TOKEN: &str = "sentinel-env-token-b6";
/// `AWS_SECRET_ACCESS_KEY`'s literal, carried as a semantic change's
/// candidate payload — the channel a terminal reader sees.
const ENV_SECRET_ACCESS_KEY: &str = "sentinel-env-secret-access-key-b7";
/// `REGISTRY_CREDENTIAL`'s literal.
const ENV_CREDENTIAL: &str = "sentinel-env-credential-b8";

/// The body of an `RSA PRIVATE KEY` block in a run diagnostic.
const PEM_RSA: &str = "sentinel-pem-rsa-c1";
/// The body of an `EC PRIVATE KEY` block in a semantic change payload.
const PEM_EC: &str = "sentinel-pem-ec-c2";
/// The body of a `PRIVATE KEY` (PKCS#8) block in a webhook's rejection
/// message.
const PEM_PKCS8: &str = "sentinel-pem-pkcs8-c3";
/// The body of a block whose closing marker never arrives — what a log
/// line clipped mid-key looks like.
const PEM_TRUNCATED: &str = "sentinel-pem-truncated-c4";

/// A value under a Secret's `data`.
const SECRET_DATA: &str = "sentinel-secret-data-d1";
/// A value under the same Secret's `stringData`.
const SECRET_STRING_DATA: &str = "sentinel-secret-stringdata-d2";
/// A value under the `data` of a Secret a webhook patch *creates*, which
/// no final object carries.
const SECRET_IN_PATCH: &str = "sentinel-secret-in-patch-d3";

/// A kubeconfig's `client-key-data:` line, quoted into a diagnostic.
const KUBECONFIG_CLIENT_KEY_TEXT: &str = "sentinel-kubeconfig-client-key-e1";
/// The same field as an object key in a parsed payload.
const KUBECONFIG_CLIENT_KEY_FIELD: &str = "sentinel-kubeconfig-client-key-field-e2";
/// A kubeconfig's `token:` line, on the line after the one above.
const KUBECONFIG_TOKEN_TEXT: &str = "sentinel-kubeconfig-token-e3";
/// The same field as an object key.
const KUBECONFIG_TOKEN_FIELD: &str = "sentinel-kubeconfig-token-field-e4";
/// A kubeconfig user's `password` as an object key.
const KUBECONFIG_PASSWORD_FIELD: &str = "sentinel-kubeconfig-password-field-e5";

/// The one configured pointer this corpus needs: everything else is
/// caught by a built-in rule, and a corpus that leaned on configuration
/// would be proving the wrong thing (`admissionlab.yaml` has no
/// `redaction:` surface yet — see `docs/security.md`).
fn rules() -> RedactionRules {
    RedactionRules::new()
}

// ---------------------------------------------------------------------
// The salted result
// ---------------------------------------------------------------------

/// [`canonical_result`] salted with every string in [`SENTINELS`] plus a
/// real generated private key.
///
/// Placement is by *channel*, not by convenience: each sentinel sits in a
/// field a real run genuinely fills from something outside this project's
/// control — an API-server warning, a webhook's rejection message, a
/// mutating webhook's patch, a controller's condition reason, a live HTTP
/// response header, a user-written expectation reason, a captured final
/// object. A redaction pass that walked only the obvious channel (the
/// final object) fails on most of this corpus.
fn sentinel_result() -> LabResult {
    let mut result = canonical_result();

    salt_admission_fixtures(&mut result);
    salt_gateway_probe(&mut result);
    salt_run_level_channels(&mut result);

    // The policy section carries the same changes the fixtures do, so it
    // is rebuilt from them: a pass that walked `fixtures` and stopped
    // would otherwise leave the run-wide list unredacted.
    result.policy.changes = result
        .fixtures
        .iter()
        .flat_map(|fixture| fixture.changes.iter().cloned())
        .collect();

    result
}

/// The three admission fixtures: a captured final object, an API-server
/// warning, a mutating webhook's patch, a change payload, a divergence
/// explanation, a webhook diagnostic, and a rejection message.
fn salt_admission_fixtures(result: &mut LabResult) {
    // --- fixture 0: the critical admission comparison ---------------
    let critical = &mut result.fixtures[0];
    let admission = critical
        .admission
        .as_mut()
        .expect("the critical fixture always has an admission comparison");

    admission.candidate.final_object = Some(sentinel_final_object());
    admission.candidate.warnings.push(format!(
        "upstream replied 401; the request line was\nAuthorization: Bearer \
         {AUTHORIZATION_TEXT}\nand the proxy hop added\nProxy-Authorization: Basic \
         {PROXY_AUTHORIZATION_TEXT}\nbefore retrying"
    ));
    admission
        .candidate
        .warnings
        .push(format!("X-Api-Key: {API_KEY_TEXT}"));
    admission.candidate.trace.invocations[0].patch = Some(vec![
        json_patch::PatchOperation::Add(json_patch::AddOperation {
            path: "/spec/template/spec/containers/1/env/0"
                .parse()
                .expect("a literal RFC 6901 pointer parses"),
            value: json!({"name": "API_TOKEN", "value": ENV_TOKEN}),
        }),
        json_patch::PatchOperation::Add(json_patch::AddOperation {
            path: "/items/-"
                .parse()
                .expect("a literal RFC 6901 pointer parses"),
            value: json!({
                "apiVersion": "v1",
                "kind": "Secret",
                "metadata": {"name": "injected-registry-pull"},
                "data": {".dockerconfigjson": SECRET_IN_PATCH}
            }),
        }),
    ]);

    let change = &mut critical.changes[0].change;
    change.baseline = Some(json!({"name": "AWS_SECRET_ACCESS_KEY", "value": "previous-value"}));
    change.candidate = Some(json!({
        "name": "AWS_SECRET_ACCESS_KEY",
        "value": ENV_SECRET_ACCESS_KEY
    }));
    if let Some(origin) = change.origin.as_mut() {
        origin.explanation =
            format!("the candidate patch set it after replaying\nX-Api-Key: {API_KEY_MAP}");
    }

    // --- fixture 1: PEM material in a change payload -----------------
    let expected = &mut result.fixtures[1];
    expected.changes[0].change.baseline = Some(json!(format!(
        "-----BEGIN EC PRIVATE KEY-----\n{PEM_EC}\n-----END EC PRIVATE KEY-----"
    )));
    let expected_admission = expected
        .admission
        .as_mut()
        .expect("the expected fixture always has an admission comparison");
    expected_admission.baseline.diagnostics[0].message = format!(
        "the webhook's own bootstrap wrote\n-----BEGIN PRIVATE KEY-----\n{PEM_PKCS8}\n-----END \
         PRIVATE KEY-----\nand the log was clipped at\n-----BEGIN OPENSSH PRIVATE KEY-----\n\
         {PEM_TRUNCATED}"
    );
    if let Some(divergence) = expected_admission.first_divergence.as_mut() {
        divergence.explanation = format!(
            "the two traces are identical; the candidate's own client config held\n\
             client-key-data: {KUBECONFIG_CLIENT_KEY_TEXT}\ntoken: {KUBECONFIG_TOKEN_TEXT}"
        );
    }

    // --- fixture 3: a webhook's rejection message --------------------
    let identical_admission = result.fixtures[3]
        .admission
        .as_mut()
        .expect("the identical fixture always has an admission comparison");
    for side in [
        &mut identical_admission.baseline,
        &mut identical_admission.candidate,
    ] {
        side.decision = admissionlab_admission::AdmissionDecision::Rejected {
            code: Some(403),
            message: format!(
                "denied: the pod's imagePullSecret resolved to\npassword: \
                 {KUBECONFIG_PASSWORD_FIELD}"
            ),
        };
    }
}

/// A live data plane's response headers — the one channel in the document
/// that carries headers a *server this project did not write* chose to
/// send.
fn salt_gateway_probe(result: &mut LabResult) {
    let gateway = result.fixtures[4]
        .gateway
        .as_mut()
        .expect("the gateway fixture always carries a comparison");
    let probe = gateway
        .candidate
        .probes
        .first_mut()
        .expect("the gateway case always answers at least one probe");
    probe
        .response_headers
        .insert("set-cookie".to_owned(), format!("session={SET_COOKIE_KEY}"));
    probe
        .response_headers
        .insert("x-auth-token".to_owned(), AUTH_TOKEN_KEY.to_owned());
}

/// The channels that hang off the run rather than off a fixture: a
/// diagnostic and its public context, a stale expectation's reason, and a
/// user-written migration expectation.
fn salt_run_level_channels(result: &mut LabResult) {
    result.diagnostics[0].message = format!(
        "installer output quoted the generated kubeconfig:\n    client-key-data: \
         {KUBECONFIG_CLIENT_KEY_TEXT}\n    token: {KUBECONFIG_TOKEN_TEXT}\nwhich it should not \
         have"
    );
    result.diagnostics[0].context.insert(
        "warning".to_owned(),
        RedactedValue::Public(format!(
            "-----BEGIN RSA PRIVATE KEY-----\n{PEM_RSA}\n-----END RSA PRIVATE KEY-----"
        )),
    );
    result.policy.stale_expectations[0].reason = format!(
        "no matching change was observed; the recorded session was\nCookie: sid={COOKIE_TEXT}"
    );

    // The real thing, from the same call the Gateway suite makes: a
    // private key this project generates for itself, in a user-written
    // field that reaches every renderer.
    result.migration.as_mut().expect("a migration case")[0].unmatched_expectations[0].reason = format!(
        "kept until the rollout is confirmed; the retired listener key was\n{}",
        test_ca_key_pem()
    );
}

/// The candidate side's final object: one document carrying a Secret, a
/// pod whose containers hold every credential-name shape, a captured
/// header map, and a kubeconfig parsed into structure.
fn sentinel_final_object() -> Value {
    json!({
        "apiVersion": "v1",
        "kind": "List",
        "items": [
            {
                "apiVersion": "v1",
                "kind": "Secret",
                "metadata": {"name": "app-credentials"},
                "data": {"password": SECRET_DATA},
                "stringData": {"apiToken": SECRET_STRING_DATA}
            },
            {
                "apiVersion": "v1",
                "kind": "Pod",
                "metadata": {"name": "app"},
                "spec": {
                    "containers": [
                        {
                            "name": "app",
                            "image": "registry.example.com/app:2.0.0",
                            "env": [
                                {"name": "DB_PASSWORD", "value": ENV_PASSWORD},
                                {"name": "MYSQL_PASSWD", "value": ENV_PASSWD},
                                {"name": "SERVICE_PWD", "value": ENV_PWD},
                                {"name": "SMTP_PASS", "value": ENV_PASS},
                                {"name": "TLS_PASSPHRASE", "value": ENV_PASSPHRASE},
                                {"name": "REGISTRY_CREDENTIAL", "value": ENV_CREDENTIAL},
                                {
                                    "name": "DB_HOST",
                                    "valueFrom": {
                                        "secretKeyRef": {"name": "app-credentials", "key": "host"}
                                    }
                                }
                            ]
                        }
                    ]
                }
            }
        ],
        "status": {
            "observedHeaders": {
                "authorization": format!("Bearer {AUTHORIZATION_KEY}"),
                "content-type": "application/json"
            },
            "resolvedClientConfig": {
                "client-certificate-data": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t",
                "client-key-data": KUBECONFIG_CLIENT_KEY_FIELD,
                "token": KUBECONFIG_TOKEN_FIELD
            }
        }
    })
}

/// A real PEM private key, generated exactly the way a Gateway TLS suite
/// generates the one it installs into the disposable cluster.
///
/// Using the real call rather than a hand-written lookalike is the point:
/// if `admissionlab_gateway`'s key encoding ever changed to a label this
/// project's PEM rule does not recognize, a lookalike would keep passing
/// and this does not.
/// Generated **once per test binary** and shared: every call mints a
/// fresh key, so a test that generated one key for the corpus and another
/// for the needle would be searching for a string that was never planted
/// — which is a test that can only pass.
fn test_ca_key_pem() -> &'static str {
    static KEY: OnceLock<String> = OnceLock::new();
    KEY.get_or_init(|| {
        let certificate =
            admissionlab_gateway::generate_test_certificate("sentinel.admissionlab.test")
                .expect("a host under the test TLD always yields a certificate");
        String::from_utf8(certificate.expose_key_pem().to_vec())
            .expect("a generated PEM key is valid UTF-8")
    })
}

/// The longest all-alphanumeric run inside `key_pem`'s base64 body, used
/// as the needle for the generated key.
///
/// Alphanumeric-only so that no renderer's escaping can rewrite it: a
/// base64 body can contain `+` and `/`, neither of which any of these
/// four renderers escapes today, but a needle that depends on that is a
/// needle that can fail for a reason unrelated to redaction.
fn key_needle(key_pem: &str) -> String {
    let needle = key_pem
        .lines()
        .filter(|line| !line.starts_with("-----"))
        .flat_map(|line| line.split(|c: char| !c.is_ascii_alphanumeric()))
        .max_by_key(|run| run.len())
        .unwrap_or_default()
        .to_owned();
    assert!(
        needle.len() >= 16,
        "a generated key's base64 body must contain a long alphanumeric run to search for; \
         got {needle:?}"
    );
    needle
}

// ---------------------------------------------------------------------
// Rendering every artifact
// ---------------------------------------------------------------------

/// One rendered artifact: the name a failure should name, and its bytes.
struct Rendered {
    name: &'static str,
    text: String,
}

/// A temporary directory that removes itself when dropped.
///
/// A test holds one for as long as it uses paths underneath it. `Drop`
/// runs on a panicking assertion too, which an explicit delete at the
/// end of a test does not — that is what keeps a `cargo test` run from
/// leaving a directory per test behind in the system temp directory.
struct TempDir(PathBuf);

impl TempDir {
    /// The directory's path, valid for as long as this guard lives.
    fn path(&self) -> &Path {
        &self.0
    }
}

impl Drop for TempDir {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

/// A fresh, guaranteed-unique directory under the system temp directory,
/// following the same convention as this crate's other filesystem tests.
fn unique_temp_dir(label: &str) -> TempDir {
    static COUNTER: AtomicU64 = AtomicU64::new(0);
    let n = COUNTER.fetch_add(1, Ordering::Relaxed);
    let dir = std::env::temp_dir().join(format!(
        "admissionlab-report-sentinel-test-{}-{label}-{n}",
        std::process::id()
    ));
    std::fs::create_dir_all(&dir).expect("create unique temp dir");
    TempDir(dir)
}

/// Every artifact a run produces, rendered from `result`.
///
/// The two file-writing renderers are exercised through their *writing*
/// entry points and read back from disk, not through an in-memory
/// shortcut: what an operator attaches to an issue is the file, and a
/// writer that serialized something other than what it rendered would
/// pass an in-memory check.
fn render_every_artifact(result: &LabResult, label: &str) -> Vec<Rendered> {
    let dir = unique_temp_dir(label);

    let json_path = dir.path().join("result.json");
    write_json_report(&json_path, result).expect("the JSON report writes");
    let json_text = std::fs::read_to_string(&json_path).expect("the JSON report reads back");

    let html_path = dir.path().join("report.html");
    write_html_report(&html_path, result).expect("the HTML report writes");
    let html_text = std::fs::read_to_string(&html_path).expect("the HTML report reads back");

    // Self-cleaning: `dir` removes itself when this function returns, and
    // the assertions below run on the text, not the files.

    vec![
        Rendered {
            name: "redact_result -> serde_json",
            text: serde_json::to_string(result).expect("a LabResult always serializes"),
        },
        Rendered {
            name: "write_json_report",
            text: json_text,
        },
        Rendered {
            name: "render_terminal",
            text: render_terminal(result, &TerminalOptions::for_stream(false, true)),
        },
        Rendered {
            name: "write_html_report",
            text: html_text,
        },
        Rendered {
            name: "render_github_summary",
            text: render_github_summary(result),
        },
    ]
}

/// The sentinels `artifact` actually contains — a renderer's *reach*.
fn reached(artifact: &Rendered, key_needle: &str) -> Vec<String> {
    SENTINELS
        .iter()
        .map(|sentinel| (*sentinel).to_owned())
        .chain(std::iter::once(key_needle.to_owned()))
        .filter(|needle| artifact.text.contains(needle.as_str()))
        .collect()
}

// ---------------------------------------------------------------------
// The proof
// ---------------------------------------------------------------------

#[test]
fn no_renderer_emits_any_sentinel_after_redaction() {
    let needle = key_needle(test_ca_key_pem());
    let redacted = redact_result(&sentinel_result(), &rules());

    for artifact in render_every_artifact(&redacted, "redacted") {
        let leaked = reached(&artifact, &needle);
        assert!(
            leaked.is_empty(),
            "{} leaked {leaked:?}; rendered output was:\n{}",
            artifact.name,
            artifact.text
        );
    }
}

#[test]
fn the_json_renderer_reaches_every_sentinel() {
    // The corpus's own non-vacuity check, and the strictest form of it:
    // `result.json` carries the whole document, so every sentinel and the
    // generated key must be present *before* redaction. A sentinel this
    // file declares but never plants fails here rather than silently
    // making one absence assertion meaningless.
    let needle = key_needle(test_ca_key_pem());
    let unredacted = sentinel_result();

    let artifacts = render_every_artifact(&unredacted, "unredacted");
    let json = artifacts
        .iter()
        .find(|artifact| artifact.name == "write_json_report")
        .expect("the JSON artifact is always rendered");

    for sentinel in SENTINELS {
        assert!(
            json.text.contains(sentinel),
            "the unredacted corpus is missing {sentinel}; every absence assertion for it would \
             then pass for the wrong reason"
        );
    }
    assert!(
        json.text.contains(&needle),
        "the unredacted corpus is missing the generated private key's body"
    );
}

#[test]
fn every_renderer_reaches_some_sentinel_before_redaction() {
    // The other three renderers show less than the whole document by
    // design (the terminal summarizes, the GitHub summary truncates), so
    // what is pinned here is that each of them reaches *something*: a
    // renderer that stopped showing payloads would satisfy the absence
    // test above for a reason that has nothing to do with redaction.
    let needle = key_needle(test_ca_key_pem());

    for artifact in render_every_artifact(&sentinel_result(), "reach") {
        let reach = reached(&artifact, &needle);
        assert!(
            !reach.is_empty(),
            "{} rendered none of the planted secrets even before redaction, so its absence \
             assertion proves nothing; rendered output was:\n{}",
            artifact.name,
            artifact.text
        );
    }
}

#[test]
fn redaction_preserves_every_finding_and_its_shape() {
    // Global Constraint 15. The whole corpus above is satisfiable by a
    // pass that returned an empty document; this is what forbids it.
    let original = sentinel_result();
    let redacted = redact_result(&original, &rules());

    assert_eq!(redacted.summary, original.summary);
    assert_eq!(
        redacted.summary,
        RunSummary::from_fixtures(&redacted.fixtures),
        "the redacted document's own fixtures must still count to its summary"
    );
    assert_eq!(redacted.policy.disposition, original.policy.disposition);
    assert_eq!(redacted.fixtures.len(), original.fixtures.len());
    assert_eq!(redacted.policy.changes.len(), original.policy.changes.len());
    assert_eq!(redacted.diagnostics.len(), original.diagnostics.len());

    for (after, before) in redacted.fixtures.iter().zip(&original.fixtures) {
        assert_eq!(after.fixture_id, before.fixture_id);
        assert_eq!(after.bucket(), before.bucket());
        assert_eq!(after.changes.len(), before.changes.len());
        for (after, before) in after.changes.iter().zip(&before.changes) {
            assert_eq!(after.severity, before.severity);
            assert_eq!(after.expected, before.expected);
            assert_eq!(after.change.kind, before.change.kind);
            assert_eq!(after.change.object_path, before.change.object_path);
            assert_eq!(after.change.subject, before.change.subject);
            assert_eq!(
                after.change.baseline.is_some(),
                before.change.baseline.is_some(),
                "a payload may be blanked but never dropped: the existence of a difference is \
                 the evidence this tool reports"
            );
            assert_eq!(
                after.change.candidate.is_some(),
                before.change.candidate.is_some()
            );
        }
    }
}

#[test]
fn every_redacted_location_still_shows_that_something_was_there() {
    // Field names, container names, header names and environment variable
    // names all survive. A reader of the redacted document can still see
    // *which* credential moved and *where*, which is the difference
    // between a redacted report and a useless one.
    let redacted = redact_result(&sentinel_result(), &rules());
    let final_object = redacted.fixtures[0]
        .admission
        .as_ref()
        .expect("the critical fixture has an admission comparison")
        .candidate
        .final_object
        .clone()
        .expect("the corpus plants a final object");

    let secret = &final_object["items"][0];
    assert_eq!(secret["metadata"]["name"], json!("app-credentials"));
    assert_eq!(secret["data"], json!({"password": REDACTED}));
    assert_eq!(secret["stringData"], json!({"apiToken": REDACTED}));

    let env = &final_object["items"][1]["spec"]["containers"][0]["env"];
    for (index, name) in [
        "DB_PASSWORD",
        "MYSQL_PASSWD",
        "SERVICE_PWD",
        "SMTP_PASS",
        "TLS_PASSPHRASE",
        "REGISTRY_CREDENTIAL",
    ]
    .into_iter()
    .enumerate()
    {
        assert_eq!(
            env[index],
            json!({"name": name, "value": REDACTED}),
            "the variable's name and its position must survive; only the literal goes"
        );
    }
    assert_eq!(
        env[6],
        json!({
            "name": "DB_HOST",
            "valueFrom": {"secretKeyRef": {"name": "app-credentials", "key": "host"}}
        }),
        "a `valueFrom` reference holds no literal and must be carried verbatim"
    );

    let headers = &final_object["status"]["observedHeaders"];
    assert_eq!(headers["authorization"], json!(REDACTED));
    assert_eq!(headers["content-type"], json!("application/json"));

    let client_config = &final_object["status"]["resolvedClientConfig"];
    assert_eq!(client_config["client-key-data"], json!(REDACTED));
    assert_eq!(client_config["token"], json!(REDACTED));
    assert_eq!(
        client_config["client-certificate-data"],
        json!("LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t"),
        "a certificate is public material a reader may need; only the key half goes"
    );

    // The PEM channel keeps the sentence around the block, and says a
    // private key was there rather than merely dropping it.
    let diagnostic = &redacted.diagnostics[0].message;
    assert!(diagnostic.starts_with("installer output quoted the generated kubeconfig:"));
    assert!(
        diagnostic.contains(&format!("client-key-data: {REDACTED}")),
        "the field name stays, the value goes: {diagnostic}"
    );
    assert!(diagnostic.ends_with("which it should not have"));

    let expected_diagnostic = &redacted.fixtures[1]
        .admission
        .as_ref()
        .expect("the expected fixture has an admission comparison")
        .baseline
        .diagnostics[0]
        .message;
    assert_eq!(
        expected_diagnostic.matches(REDACTED_PRIVATE_KEY).count(),
        2,
        "both the complete PKCS#8 block and the truncated one must be replaced, and the \
         replacement must say a private key was there: {expected_diagnostic}"
    );

    // A live response header keeps its name, so a header present on one
    // side and absent on the other is still a visible difference.
    let probe = &redacted.fixtures[4]
        .gateway
        .as_ref()
        .expect("the gateway fixture carries a comparison")
        .candidate
        .probes[0];
    assert_eq!(probe.response_headers["set-cookie"], REDACTED);
    assert_eq!(probe.response_headers["x-auth-token"], REDACTED);
    assert_eq!(probe.status, 503, "an observed status is not a secret");
}

#[test]
fn the_corpus_is_redacted_idempotently_and_without_mutating_its_input() {
    let original = sentinel_result();
    let snapshot = original.clone();

    let once = redact_result(&original, &rules());
    let twice = redact_result(&once, &rules());

    assert_eq!(
        original, snapshot,
        "redact_result must leave its argument untouched"
    );
    assert_eq!(
        once, twice,
        "redacting an already-redacted result must be a no-op, because nothing in the pipeline \
         tracks whether a given result has been through the pass"
    );
}

/// Prints each renderer's reach, for a human reviewing what this file
/// actually proves about each artifact.
///
/// `#[ignore]`d because it asserts nothing — it is the diagnostic behind
/// [`every_renderer_reaches_some_sentinel_before_redaction`], and the
/// numbers it prints are what a reviewer needs in order to judge how
/// strong each renderer's absence assertion is. At the time of writing:
/// `result.json` reaches all of them, `report.html` all but the four
/// carried only by a Gateway probe header and a rejection message, the
/// terminal summary five, and the GitHub step summary one (it lists
/// findings, truncated at `MAX_CELL_CHARS`).
///
/// Run with
/// `cargo test -p admissionlab-report --test security_sentinels -- --ignored --nocapture`.
#[test]
#[ignore = "diagnostic: prints each renderer's sentinel reach rather than asserting"]
fn print_each_renderers_reach() {
    let needle = key_needle(test_ca_key_pem());
    for artifact in render_every_artifact(&sentinel_result(), "reach-report") {
        let reach = reached(&artifact, &needle);
        println!(
            "{}: {} of {}\n  {reach:?}",
            artifact.name,
            reach.len(),
            SENTINELS.len() + 1
        );
    }
}
